# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balancelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(default=1)),
                ('correlationid', models.IntegerField()),
                ('money', models.FloatField()),
                ('changetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'balancelog',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=30)),
                ('logourl', models.CharField(max_length=100, null=True)),
                ('describe', models.CharField(max_length=200, null=True)),
                ('brandstatus', models.BooleanField(default=False)),
                ('orderby', models.IntegerField()),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=30)),
                ('parentid', models.IntegerField(default=0)),
                ('classgrade', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecttime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=30)),
                ('barcode', models.CharField(max_length=50)),
                ('oneclassid', models.IntegerField()),
                ('twoclassid', models.IntegerField()),
                ('threeclassid', models.IntegerField()),
                ('upstatus', models.BooleanField(default=False)),
                ('producttime', models.CharField(max_length=30)),
                ('validity', models.CharField(max_length=5)),
                ('describe', models.CharField(max_length=200, null=True)),
                ('brand', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='App.Brand')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Gradelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.BooleanField(default=False)),
                ('correlationid', models.IntegerField()),
                ('num', models.IntegerField(default=5)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gradelog',
            },
        ),
        migrations.CreateModel(
            name='Loginlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(auto_now_add=True)),
                ('loginip', models.CharField(max_length=15)),
                ('logintype', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'loginlog',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=30, unique=True)),
                ('linkman', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'logistics',
            },
        ),
        migrations.CreateModel(
            name='Lookhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(unique=True)),
                ('onumber', models.CharField(max_length=30, unique=True)),
                ('getername', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('paymothod', models.IntegerField(default=1)),
                ('money', models.FloatField()),
                ('lname', models.CharField(max_length=30)),
                ('lnumber', models.CharField(max_length=30, unique=True)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('delivertime', models.DateTimeField(null=True)),
                ('paytime', models.DateTimeField(null=True)),
                ('orderstatus', models.IntegerField()),
                ('grade', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('gid', models.IntegerField()),
                ('gname', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('unitprice', models.FloatField()),
                ('weight', models.FloatField()),
                ('offmoney', models.FloatField()),
                ('wid', models.IntegerField()),
            ],
            options={
                'db_table': 'orderdetails',
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('place', models.CharField(max_length=30)),
                ('fragrance', models.CharField(max_length=30)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=30)),
                ('character', models.CharField(max_length=30)),
                ('person', models.CharField(max_length=30)),
                ('pack', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('goods', models.OneToOneField(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods')),
            ],
            options={
                'db_table': 'perfume',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('main', models.IntegerField()),
                ('order_by', models.IntegerField()),
                ('valid', models.IntegerField()),
                ('goods', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods')),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='Repertory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('wid', models.IntegerField(unique=True)),
                ('nowcount', models.IntegerField()),
            ],
            options={
                'db_table': 'repertory',
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods')),
            ],
            options={
                'db_table': 'shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=30)),
                ('taste', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('place', models.CharField(max_length=30)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('safetime', models.CharField(max_length=30)),
                ('allow_number', models.IntegerField()),
                ('pack', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('goods', models.OneToOneField(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods')),
            ],
            options={
                'db_table': 'snacks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('sex', models.BooleanField(default=True)),
                ('ugrade', models.IntegerField(default=0)),
                ('regtime', models.DateTimeField(auto_now_add=True)),
                ('brithday', models.CharField(max_length=12, null=True)),
                ('balance', models.FloatField(default=0)),
                ('usertype', models.BooleanField(default=False)),
                ('papers', models.CharField(default='身份证', max_length=5)),
                ('papersid', models.CharField(max_length=23)),
                ('picture', models.CharField(default='/static/app/images/default.jpg', max_length=300)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Useraddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('district', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('isdefault', models.BooleanField(default=False)),
                ('changetime', models.DateTimeField(auto_now=True)),
                ('consignee', models.CharField(max_length=5, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('tel', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('postcode', models.IntegerField(null=True)),
                ('user', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
            options={
                'db_table': 'useraddr',
            },
        ),
        migrations.CreateModel(
            name='Userlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelname', models.CharField(max_length=10)),
                ('mingrade', models.IntegerField()),
                ('maxgrade', models.IntegerField()),
            ],
            options={
                'db_table': 'userlevel',
            },
        ),
        migrations.CreateModel(
            name='Warehouseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warename', models.CharField(max_length=30, unique=True)),
                ('linkman', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'warehouseinfo',
            },
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='lookhistory',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='gradelog',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='collect',
            name='goods',
            field=models.ForeignKey(db_column='gid', on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
        migrations.AddField(
            model_name='balancelog',
            name='user',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
    ]
