# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collect',
            table='collect',
        ),
        migrations.AlterModelTable(
            name='lookhistory',
            table='lookhistory',
        ),
    ]
