# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190703_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookhistory',
            name='looktime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
