# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_lookhistory_looktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='lookcount',
            field=models.IntegerField(default=0),
        ),
    ]
