# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-06 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_goods_lookcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='repertory',
            name='wid',
            field=models.IntegerField(),
        ),
    ]
