# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190706_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cid',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(db_column='cid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Category'),
        ),
    ]
