# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190707_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='goods',
            field=models.OneToOneField(db_column='gid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='goods',
            field=models.OneToOneField(db_column='gid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
    ]
