# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20190707_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='collecttime',
        ),
    ]
