# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_collect_collecttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='collecttime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
