# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_collect_collecttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='user',
        ),
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
