# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
    ]
