# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-07 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20190707_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='goods',
            field=models.ForeignKey(db_column='gid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
    ]
