# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20190707_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
