# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_order_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderdetails',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oid',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='gname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.OneToOneField(db_column='gid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
        migrations.AddField(
            model_name='order',
            name='unitprice',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='wid',
            field=models.IntegerField(default=1),
        ),
    ]
