# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20190708_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lname',
            field=models.CharField(default='申通快递', max_length=30),
        ),
    ]
