# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-08 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20190708_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gname',
        ),
    ]
