# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_remove_order_gname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(db_column='gid', null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.IntegerField(default=2),
        ),
    ]
