# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20190709_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftime', models.DateTimeField()),
                ('view', models.IntegerField()),
            ],
            options={
                'db_table': 'flow',
            },
        ),
    ]
