# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-10 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20190709_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='regtime',
        ),
    ]
